name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 15.x]
        mongodb-version: [5.0.0]
        database-name:
          - codely
        database-user:
          - codely
        database-password:
          - codely
        database-host:
          - localhost
        database-port:
          - 5432
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ matrix.database-user }}
          POSTGRES_PASSWORD: ${{ matrix.database-password }}
          POSTGRES_DB: ${{ matrix.database-name }}
        ports:
          - ${{ matrix.database-port }}:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: wbari/start-mongoDB@v0.2
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: npm install
        run: |
          npm install
      - name: npm run build
        run: |
          npm run build --if-present
          npm run lint
      - name: setup test database
        env:
          DATABASE_NAME: ${{ matrix.database-name }}
          DATABASE_USER: ${{ matrix.database-user }}
          DATABASE_PASSWORD: ${{ matrix.database-password }}
          DATABASE_HOST: ${{ matrix.database-host }}
          DATABASE_PORT: ${{ matrix.database-port }}
        run: |
          npm run test
      - name: npm test
        run: |
          npm test
